spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: hello-world
          uri: https://httpbin.org
          predicates:
            - Path=/hello
          filters:
            - SetPath=/get
